# Generated by Django 3.0.3 on 2020-02-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
